feat(cip2): add functions to create selection constraints
input-output-hk/cardano-js-sdk pull request #100
Opened 2021-09-28 06:41 UTC by mkazlauskas

# Context

Since the CIP2 package is dependent on the CSL, we may as well include functions to cover the selection constraints:

- computeMinimumCost
- tokenBundleSizeExceedsLimit
- computeMinimumCoinQuantity
- computeSelectionLimit

# Proposed Solution

Implement default selection constraints and export them from cip2 package. Use as defaults in coin selection if applicable.

# Important Changes Introduced

2021-09-28 08:58 UTC, rhyslbw reviewed
Looks good so far :+1:

2021-09-28 08:58 UTC, rhyslbw commented on packages/cip2/src/types.ts
> +export type ComputeMinimumCoinQuantity = (assetQuantities?: CSL.MultiAsset) => bigint;
Good catch

2021-09-28 08:58 UTC, rhyslbw commented on packages/cip2/src/selectionConstraints.ts
> +    const minUTxOValue = CSL.BigNum.from_str((BigInt(coinsPerUtxoWord) * 29n).toString());
```suggestion
    const minUTxOValue = CSL.BigNum.from_str((coinsPerUtxoWord * 29).toString());
```
Does this need to be a `bigint`?

2021-09-29 07:16 UTC, rhyslbw requested changes
Need to also export the constraints from the package index:
```
export * as selectionConstraints from './selectionConstraints';
```

2021-09-29 07:37 UTC, mkazlauskas commented on packages/cip2/src/selectionConstraints.ts
> +    const minUTxOValue = CSL.BigNum.from_str((coinsPerUtxoWord * 29).toString());
This is actually now a tsc error after I rebased on master.  No more mistakes like that

2021-09-29 09:48 UTC, mkazlauskas commented
@rhyslbw I'm finished with this for the time being. Please review and let me know if you want me to do any changes.

I've changed my mind about needing serialization/size tests right now. It's probably out of scope for this repo and we should be trusting CSL. Let me know if you think otherwise.

Also, do you think there's any new code in this PR worth moving to core package? I could think of a few pieces but I'm not sure they'd ever be used. I'm thinking to refactor as needed if we start duplicating code, like with `ogmiosToCsl.value()`.

2021-09-29 10:37 UTC, rhyslbw approved these changes
Great work @mkazlauskas 

> I've changed my mind about needing serialization/size tests right now. It's probably out of scope for this repo and we should be trusting CSL. Let me know if you think otherwise

Agree. These were always going to be sanity checks, but this can also be done as once-off manual QA.

> Also, do you think there's any new code in this PR worth moving to core package? I could think of a few pieces but I'm not sure they'd ever be used. I'm thinking to refactor as needed if we start duplicating code, like with ogmiosToCsl.value().

Nothing jumps out, so let's do it on-demand.

2021-09-29 10:39 UTC, merged