Feat/lw 9535 configurable metadata job retry delay
input-output-hk/cardano-js-sdk pull request #1048
Opened 2024-01-15 14:18 UTC by iccicci

# Context

Latest applied changes in the SDK introduced some delays in fetching stake pool metadata. Since the default retry delay for the job which fetches the metadata is tailored for `live-mainnet` no retries are performed during the rebuild fixtures procedure.

The sum of this two facts makes the newly generated fixtures missing the metadata.

# Proposed Solution

- made the retry delay for the job configurable
- configured said delay to 60" in `local-network`

# TODO

I've regenerated the fixtures to have confirmation from CI as well everything went as expected, but this change doesn't actually need a fixtures regeneration.

I'll remove the last commit in the final squash/rebase stage to make the merge with `conway-era` branch more easy.

2024-01-15 14:25 UTC, mkazlauskas requested changes
Looks good! Just please squash the 1st two commits and mark it as breaking change due to rename of operator exported from `projection-typeorm`

2024-01-16 13:54 UTC, rhyslbw submitted a review, later dismissed
Nice work @iccicci 🦾

2024-01-16 15:55 UTC, rhyslbw approved these changes

2024-01-17 06:09 UTC, mkazlauskas approved these changes
Nice work! :rocket: 

Just a note (no action needed): when commit message header doesn't describe the breaking change, it's better to use `BREAKING CHANGE:` footer to describe it separately instead of `!`

2024-01-17 08:44 UTC, merged