feat: remove async from fromBip39Entropy
input-output-hk/cardano-js-sdk pull request #1326
Opened 2024-06-10 07:46 UTC by jinglescode

# Context

functions like [`fromBip39Entropy()`](https://github.com/input-output-hk/cardano-js-sdk/blob/master/packages/crypto/src/Bip32/Bip32PrivateKey.ts#L80) are essential for them to operate without being async, so upstream functions do not required async.

# Proposed Solution

`pbkdf2` replace with `pbkdf2Sync`

# Important Changes Introduced

- functions using `fromBip39Entropy()` can remove `await`

2024-06-10 09:05 UTC, mkazlauskas requested changes
Thanks for contribution! :heart: Please also update the usages to not await:
![image](https://github.com/input-output-hk/cardano-js-sdk/assets/2457868/95e3d478-e66b-41ea-b4ca-77a3f9c2d349)

Also it would be great to align the [Bip32Ed25519 interface](https://github.com/input-output-hk/cardano-js-sdk/blob/master/packages/crypto/src/Bip32Ed25519.ts#L32)

2024-06-10 09:05 UTC, mkazlauskas commented on packages/crypto/src/Bip32/Bip32PrivateKey.ts
> +      password,
Lint error here

2024-06-11 05:12 UTC, mkazlauskas reviewed
Changes looks good! Need to resolve CI errors before merging, currently at

```
crypto/src/strategies/CmlBip32Ed25519.ts(24,10): error TS2416: Property 'fromBip39Entropy' in type 'CmlBip32Ed25519' is not assignable to the same property in base type 'Bip32Ed25519'.
```

which is probably asking to update async->sync in `CmlBip32Ed25519`

https://github.com/input-output-hk/cardano-js-sdk/actions/runs/9448898910/job/26053476806?pr=1326#step:4:178

2024-06-11 06:23 UTC, jinglescode commented
> Changes looks good! Need to resolve CI errors before merging, currently at
> 
> ```
> crypto/src/strategies/CmlBip32Ed25519.ts(24,10): error TS2416: Property 'fromBip39Entropy' in type 'CmlBip32Ed25519' is not assignable to the same property in base type 'Bip32Ed25519'.
> ```
> 
> which is probably asking to update async->sync in `CmlBip32Ed25519`
> 
> https://github.com/input-output-hk/cardano-js-sdk/actions/runs/9448898910/job/26053476806?pr=1326#step:4:178

Yea I saw the build error this morning and wanted to fix this this afternoon. So just pushed, and gonna see if this fixes it.

2024-06-19 14:58 UTC, AngelCastilloB approved these changes
LGTM!

2024-06-19 15:06 UTC, mkazlauskas approved these changes

2024-06-19 15:06 UTC, merged