Lw 10449 sdk e2e tests ci
input-output-hk/cardano-js-sdk pull request #1332
Opened 2024-06-13 17:56 UTC by ce0la

# Context
Background
An easy to run CI action should be available to quickly sanitize SRE deployments (e.g. dev-preprod).

DoD
CI action can be run targeting different deployments.

An env variable (or such) should be configurable to determine which deployment we are targeting

…
https://input-output.atlassian.net/browse/LW-10449
_Reason for the change? If an issue exists, reference it here using a [keyword](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)_

# Proposed Solution

# Important Changes Introduced

2024-06-14 08:32 UTC, gytis-ivaskevicius requested changes
KEY_MANAGEMENT_PARAMS needs to be fixed, other than that if it works - its good

2024-06-14 08:32 UTC, gytis-ivaskevicius commented on .github/workflows/continuous-integration-e2e.yaml
> +          KEY_MANAGEMENT_PARAMS=${{ secrets.KEY_MANAGEMENT_PARAMS }}
this one changes depending on network

2024-06-14 08:32 UTC, gytis-ivaskevicius commented on .github/workflows/continuous-integration-e2e.yaml
> +          source .env
why do we need to source .env everywhere?

2024-06-14 08:32 UTC, gytis-ivaskevicius commented on packages/e2e/src/scripts/generate-network-dotenv.sh
> +network="$1"
technically this is an `environment` or `release_train`

2024-06-14 15:05 UTC, iccicci reviewed
Some notes... but great job! Thank you

2024-06-14 15:05 UTC, iccicci commented on .github/workflows/test-deploy-e2e.yaml
> +          yarn workspace @cardano-sdk/e2e wait-for-network-init
Sorry, I forgot: my bad.

These two steps must be removed.

2024-06-14 15:05 UTC, iccicci commented on .github/workflows/test-deploy-e2e.yaml
> +name: Continuous Integration - SDK E2E
I know I'm being nitpicky 😉 but this is not a `Continuous Integration` action, what about `Deployed environments - SDK E2E tests`?

2024-06-14 15:50 UTC, iccicci commented on .github/workflows/test-deploy-e2e.yaml
> +          ./src/scripts/generate-dotenv.sh ${{ inputs.environment }}
`dev-mainnet` is useless ATM, some environment in input is missing.

2024-06-14 16:11 UTC, ce0la commented on .github/workflows/test-deploy-e2e.yaml
> +          ./src/scripts/generate-dotenv.sh ${{ inputs.environment }}
A simple conditional would suffice for the two targeted networks (preprod and preview). Pushing the change now.

2024-06-14 16:13 UTC, ce0la commented on .github/workflows/test-deploy-e2e.yaml
> +          ./src/scripts/generate-dotenv.sh ${{ inputs.environment }}
https://github.com/input-output-hk/cardano-js-sdk/pull/1332/commits/9b9b6d36da52b133bee7707f3a581a8ca0e41452

2024-06-17 09:21 UTC, gytis-ivaskevicius submitted a review, later dismissed

2024-06-19 10:00 UTC, iccicci approved these changes
Exceptional job! Thank you!

2024-06-19 10:02 UTC, gytis-ivaskevicius approved these changes
Good job :)

2024-06-19 10:07 UTC, michalrus approved these changes
Nice! Thank you :)

2024-06-19 10:20 UTC, merged