LW-10279 Merge conway-era into master
input-output-hk/cardano-js-sdk pull request #1376
Opened 2024-07-19 09:50 UTC by mirceahasegan

# Context

In preparation for the Chang HF, `conway-era` will merge to `master`.

# Proposed Solution

# Important Changes Introduced

2024-07-23 13:56 UTC, mirceahasegan commented
Converted this to draft until the checklist in the description is all complete

2024-07-26 14:22 UTC, iccicci approved these changes
💪 🚀

2024-07-28 09:50 UTC, iccicci submitted a review, later dismissed

2024-07-29 06:21 UTC, mkazlauskas requested changes

2024-07-29 06:21 UTC, mkazlauskas commented on .github/workflows/continuous-integration-e2e.yaml
> +    branches: ['master', 'conway-era']
```suggestion
    branches: ['master']
```

2024-07-29 06:21 UTC, mkazlauskas commented on .github/workflows/continuous-integration-unit-tests.yaml
> +    branches: ['master', 'conway-era']
```suggestion
    branches: ['master']
```

2024-07-29 08:48 UTC, mirceahasegan commented on .github/workflows/continuous-integration-e2e.yaml
> +    branches: ['master', 'conway-era']
done: 4459ae5a468

2024-07-29 08:48 UTC, mirceahasegan commented on .github/workflows/continuous-integration-unit-tests.yaml
> +    branches: ['master', 'conway-era']
done: 4459ae5a468

2024-07-29 08:50 UTC, mkazlauskas approved these changes
The day has come! :sunglasses: :tada:

2024-07-29 08:56 UTC, iccicci approved these changes

2024-07-29 12:19 UTC, merged