feat: asset tracker now uses local cache before fetching asset metadata
input-output-hk/cardano-js-sdk pull request #1539
Opened 2024-12-02 11:11 UTC by AngelCastilloB

# Context

Everytime a new instance of base wallet the asset tracker will fetch metadata for all known assets in the transaction history. His could be thousands of assets on an active wallet, which could amount to 10 of thousand of fetches during the day.

# Proposed Solution

The asset tracker now will fetch new asset metadata only for assets that are present in balance, and only every 7 days (+-2 days of variance to avoid re-fetching them all at once)

2024-12-02 13:16 UTC, mkazlauskas requested changes

2024-12-02 13:25 UTC, AngelCastilloB commented on packages/wallet/src/services/AssetsTracker.ts
> +                  cachedAssets.set(asset.assetId, { ...asset, lastFetchedAt: new Date(Date.now() + randomDelta) });
I am randomizing the last fetch add with a delta so they dont expire at the same time

2024-12-02 13:26 UTC, AngelCastilloB commented on packages/wallet/test/services/AssetsTracker.test.ts
> +
I skip it because before the time has hard-coded to 7 days, now that is configurable I will try to come up with a way to test it

2024-12-03 04:53 UTC, AngelCastilloB commented on packages/wallet/test/services/AssetsTracker.test.ts
> +      flush();
done here https://github.com/input-output-hk/cardano-js-sdk/pull/1539/commits/d707e1ead8c3b3b821c936b7f209b62450a00c7a

2024-12-03 04:53 UTC, AngelCastilloB commented on packages/wallet/src/services/AssetsTracker.ts
> +        totalBalance$.pipe(
done here https://github.com/input-output-hk/cardano-js-sdk/pull/1539/commits/cb28d05300ce9e87547b8e41a74beaabe13a6db2

2024-12-03 04:55 UTC, AngelCastilloB commented on packages/wallet/src/services/AssetsTracker.ts
> +                  cachedAssets.set(asset.assetId, { ...asset, lastFetchedAt: new Date(Date.now() + randomDelta) });
done here https://github.com/input-output-hk/cardano-js-sdk/pull/1539/commits/c2530f284655fbed4c31d4b61cad393fcf4ff851

2024-12-03 04:56 UTC, AngelCastilloB commented on packages/wallet/src/Wallets/BaseWallet.ts
> +    const assetsCache$ = defer(() => stores.assets.get().pipe(defaultIfEmpty(new Map())));
@mkazlauskas I created a new ticket for this, and added a TODO on code. https://github.com/input-output-hk/cardano-js-sdk/pull/1539/commits/56e36a395a30dae3d55560793b8f2fa923da6580 This change requires changing the interface, implementing the method on all DocumentStores, adding unit tests etc, its probably better done as a separate ticket

2024-12-03 04:57 UTC, AngelCastilloB commented on packages/wallet/test/services/AssetsTracker.test.ts
> +
done here https://github.com/input-output-hk/cardano-js-sdk/pull/1539/commits/46d8b35c09c258f897f8dd08d8cf305f5f3f1de5

2024-12-04 12:23 UTC, mirceahasegan commented on packages/wallet/src/services/AssetsTracker.ts
> + *    - Use the cached version only if it exists and its `staleAt` timestamp already expired.
```diff
- *    - Use the cached version only if it exists and its `staleAt` timestamp already expired.
+ *    - Use the cached version only if it exists and its `staleAt` timestamp did not expire.

2024-12-04 12:28 UTC, mirceahasegan commented on packages/wallet/src/services/AssetsTracker.ts
> +const ONE_WEEK = 7 * 24 * 60 * 60 * 1000;
```diff
+ const ONE_DAY = 24 * 60 * 60 * 1000;
- const ONE_WEEK = 7 * 24 * 60 * 60 * 1000;
+ const ONE_WEEK = 7 * ONE_DAY;

2024-12-04 12:29 UTC, mirceahasegan commented on packages/wallet/src/services/AssetsTracker.ts
> +    const randomDelta = Math.floor(Math.random() * 2 * 24 * 60 * 60 * 1000); // Random time between 0 and 2 days
```diff
-    const randomDelta = Math.floor(Math.random() * 2 * 24 * 60 * 60 * 1000); // Random time between 0 and 2 days
+    const randomDelta = Math.floor(Math.random() * 2 * ONE_DAY); // Random time between 0 and 2 days

2024-12-04 12:49 UTC, AngelCastilloB commented on packages/wallet/src/services/AssetsTracker.ts
> + *    - Use the cached version only if it exists and its `staleAt` timestamp already expired.
done here https://github.com/input-output-hk/cardano-js-sdk/pull/1539/commits/aa886ba774b8123259f59767c2b15f31e4a527df

2024-12-04 12:49 UTC, AngelCastilloB commented on packages/wallet/src/services/AssetsTracker.ts
> +const ONE_WEEK = 7 * 24 * 60 * 60 * 1000;
done here https://github.com/input-output-hk/cardano-js-sdk/pull/1539/commits/aa886ba774b8123259f59767c2b15f31e4a527df

2024-12-04 12:49 UTC, AngelCastilloB commented on packages/wallet/src/services/AssetsTracker.ts
> +    const randomDelta = Math.floor(Math.random() * 2 * 24 * 60 * 60 * 1000); // Random time between 0 and 2 days
done here https://github.com/input-output-hk/cardano-js-sdk/pull/1539/commits/aa886ba774b8123259f59767c2b15f31e4a527df

2024-12-04 13:14 UTC, mkazlauskas approved these changes
Nice work! :rocket:

2024-12-04 14:44 UTC, mirceahasegan approved these changes
Fantastic work, @AngelCastilloB

2024-12-04 15:36 UTC, merged