feat: nft metadata
input-output-hk/cardano-js-sdk pull request #159
Opened 2022-01-12 15:00 UTC by mkazlauskas

# Context

As an developer integrating the SDK wallet into an application
I want to show NFT metadata
so that I can present a rich user interface for my users that includes metadata that describes the asset

# Proposed Solution

Add optional NFT metadata to `Wallet.assets$`

# Important Changes Introduced

`core` package:
- Add partial support for Byron (base58) addresses (using it in a new tx is out of scope of this PR)
- Add partial support for genesis pool IDs (using it in a new tx is out of scope of this PR)
- Add a few metadatum parsing utils
- (BREAKING) change type of Asset.name to AssetName opaque string

## Notes

Since CIP-0025 does not specify encoding for `<asset_name>`, we'll support both hex and utf8 encoded strings.

2022-01-17 09:01 UTC, iadmytro submitted a review, later dismissed

2022-01-17 21:03 UTC, lgobbi-atix requested changes

2022-01-18 14:08 UTC, mkazlauskas commented on packages/wallet/src/NftMetadata/types.ts
> +  throw new InvalidStringError('Expected Uri to start with protocol://');
Thanks for review @lgobbi-atix. I updated the error message to be clearer

2022-01-18 14:56 UTC, lgobbi-atix approved these changes

2022-01-18 16:44 UTC, merged