Refactor StakePoolBuilder tests
input-output-hk/cardano-js-sdk pull request #257
Opened 2022-05-20 20:59 UTC by jvieiro

# Context

Since Db Snapshot can be taken from different databases some autoincremental IDs can vary from db to db due to cases such rollbacks. So, instead of checking for every ID number, we would check only object's data by replacing every registry ID per a generic one

# Proposed Solution

- [x] Create RegEx to replace rows IDs per a generic one
- [x] Apply to corresponding StakePoolBuilder queries
- [x] Update Snapshot

# Important Changes Introduced

2022-05-23 10:44 UTC, rhyslbw requested changes
Can you instead just strip these fields from the object altogether? Also, retaining the prettiness of the snapshot is important, as they're verified manually.

2022-05-23 16:30 UTC, jvieiro commented
> Can you instead just strip these fields from the object altogether? Also, retaining the prettiness of the snapshot is important, as they're verified manually.

I've stripped them in most of tests. Except poolHashes query, where ids are the only result it expects.

2022-05-24 13:08 UTC, rhyslbw requested changes

2022-05-24 13:08 UTC, rhyslbw commented on packages/cardano-services/test/StakePoolSeach/DbSyncStakePoolSearchProvider/StakePoolSearchBuilder.test.ts
> +      expect(striptedIds).toMatchSnapshot();
We're not expecting the stripped IDs to match the snapshot :smile: Always think of the person reading this for the first time :+1: 
```suggestion
      expect(registrations).toMatchSnapshot();
```

2022-05-30 04:54 UTC, rhyslbw approved these changes
Thanks @jvieiro

2022-05-30 04:54 UTC, merged

2022-06-01 04:13 UTC, Newman1515 reviewed
Submit the approve
And 
Submit the review