fix(wallet): Ledger transaction submission bug fix
input-output-hk/cardano-js-sdk pull request #259
Opened 2022-05-24 10:10 UTC by tomislavhoracek

# Context
- Bugfix for transaction signing with Ledger devices when the account index is different than zero.

# Proposed Solution
Wallet user can create a single account / address wallet with any account index, and perform all wallet actions using it. In this particular case to sign and send transactions using Ledger.

# Important Changes Introduced
- Fixed witnesses preparation in LedgerKeyAgent

2022-05-24 10:16 UTC, mkazlauskas approved these changes

2022-05-24 11:42 UTC, rhyslbw requested changes
From the bug report, the expected behavior is:

> Wallet users can create a single account/address wallet with any account index, and perform all wallet actions using it. In this particular case to sign and send transactions using Ledger

Please add test coverage for this to demonstrate we're meeting the requriements.

2022-05-24 14:39 UTC, rhyslbw submitted a review, later dismissed

2022-05-24 14:48 UTC, tomislavhoracek commented on packages/wallet/src/KeyManagement/LedgerKeyAgent.ts
> +              index: witness.path[4],
Thanks @rhyslbw. I was thinking to introduce that in the scope of another PR where we introduced constants ( purpose, coin_type)
https://github.com/input-output-hk/cardano-js-sdk/blob/a7cbf49b2445eeeaa4fbae4100925f37c3d0989e/packages/wallet/src/KeyManagement/util/constants.ts#L1

2022-05-24 14:49 UTC, rhyslbw commented on packages/wallet/src/KeyManagement/LedgerKeyAgent.ts
> +              index: witness.path[4],
Great, I'll retract my CR.

2022-05-26 05:17 UTC, rhyslbw requested changes
Looks good, please squash that last commit in preparation for the final QA review

2022-05-30 12:23 UTC, mrcnk approved these changes
I ran the QA process for this bug fix on the frontend side and everything seems to be working correctly (when creating a wallet with `accountIndex` different than the first one).

2022-05-30 12:32 UTC, rhyslbw approved these changes

2022-05-30 12:36 UTC, merged