feat: add sort stake pools by saturation
input-output-hk/cardano-js-sdk pull request #270
Opened 2022-06-03 20:53 UTC by lgobbi-atix

# Context

The current sort order for results returned from the `DbSyncStakePoolProvider.queryStakePools` method is ordered by name. We require the interface to also include `saturation`.

# Proposed Solution

- Add `saturation` sort field with `desc` order as default
- Adapt `withSort` function to be able to sort queries other than `findPoolData`
- Refactor `DbSyncStakePoolProvider.queryStakePools` so it can identify which query to use to order the response

# Important Changes Introduced
- `DbSyncStakePoolProvider.queryStakePools` refactor
- Added `getQueryBySortType` private method to `DbSyncStakePoolProvider`
- Added sort by saturation to pool metrics query
- Fix a bug where sorting by name was case sensitive, leading to results like: `['CLIO1','July 2021','banderini']`
- Fix a bug where sorting by name `desc` would return pools with no name first instead of last
- Fixed tests related to those bugs

2022-06-08 12:14 UTC, mkazlauskas reviewed
Looks good overall. Query building is getting complicated (and therefore difficult to read), but I don't think there's an easy solution to that.

2022-06-08 21:36 UTC, IvayloAndonov commented on packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/DbSyncStakePool.ts
> +    const lastEpoch = await this.#builder.getLastEpoch();
What is the reason we move `getLastEpoch()` out of `Promise.all()`?

2022-06-08 21:36 UTC, IvayloAndonov commented on packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/DbSyncStakePool.ts
> +    const lastEpoch = await this.#builder.getLastEpoch();
What is the reason we move `getLastEpoch()` out of `Promise.all()`?

2022-06-08 22:04 UTC, IvayloAndonov commented on packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/DbSyncStakePool.ts
> +    this.#logger.debug('About to stake pool extra information');
```suggestion
    this.#logger.debug('About to stake pool extra information');
```
```suggestion
    this.#logger.debug('About to query stake pool extra information');
```

2022-06-08 22:04 UTC, IvayloAndonov commented on packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/DbSyncStakePool.ts
> +    this.#logger.debug('About to stake pool extra information');
```suggestion
    this.#logger.debug('About to stake pool extra information');
```
```suggestion
    this.#logger.debug('About to query stake pool extra information');
```

2022-06-08 22:27 UTC, IvayloAndonov commented on packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/mappers.ts
> +    .filter((result) => result !== undefined) as Cardano.StakePool[],
What is the case where `result` is _undefined_ here? At first look it seems we iterate over the collection `poolHashIds` (passed as `orderedResultHashIds`  which are previously filled with additional [restOfPoolData](https://github.com/input-output-hk/cardano-js-sdk/pull/270/files#diff-5ad8b26faabe50605214aec922ed96428a741e5e07da541676062cec7a693a17R74) ) which is bigger than `poolDatas`

2022-06-08 22:27 UTC, IvayloAndonov commented on packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/mappers.ts
> +    .filter((result) => result !== undefined) as Cardano.StakePool[],
What is the case where `result` is _undefined_ here? At first look it seems we iterate over the collection `poolHashIds` (passed as `orderedResultHashIds`  which are previously filled with additional [restOfPoolData](https://github.com/input-output-hk/cardano-js-sdk/pull/270/files#diff-5ad8b26faabe50605214aec922ed96428a741e5e07da541676062cec7a693a17R74) ) which is bigger than `poolDatas`

2022-06-09 05:58 UTC, IvayloAndonov commented
More of a question, considering the intense increase in complexity and theoretically more sorting fields requested in the future, do we think that maintaining modular DB queries + additional [logic](https://github.com/input-output-hk/cardano-js-sdk/pull/270/files#diff-5ad8b26faabe50605214aec922ed96428a741e5e07da541676062cec7a693a17R59-R74) populating minimum requested data for a simple operation like sort is still the better option than having one composed DB query (with joined required tables) providing [stake pool data](https://github.com/input-output-hk/cardano-js-sdk/blob/52d71a70700b05902cca6205fe01a63f811ba5af/packages/core/src/Provider/StakePoolProvider/types/StakePoolProvider.ts#L53) at once  (sorted, filtered and paginated)? 🤔

2022-06-09 11:55 UTC, rhyslbw commented
@IvayloAndonov Please create a SPIKE for further exploration of this technical debt reducer in a later sprint.

2022-06-09 11:59 UTC, rhyslbw reviewed
I expect `fix: make stake pool order by name case insensitive and move nulls to last` to be a separate commit before either a single commit with the refactor + feature, or two extra commits.

2022-06-09 19:35 UTC, lgobbi-atix commented on packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/util.ts
> +  return 'data';
Done

2022-06-09 19:38 UTC, lgobbi-atix commented
> I expect `fix: make stake pool order by name case insensitive and move nulls to last` to be a separate commit before either a single commit with the refactor + feature, or two extra commits.

I left the first commit with the refactor + feature as it's kinda hard to separate them and added a new commit after with the fix

2022-06-13 10:34 UTC, rhyslbw approved these changes
Great work @lgobbi-atix.

2022-06-13 12:31 UTC, mkazlauskas approved these changes
Looks good, nice work! :tada:

2022-06-13 12:43 UTC, IvayloAndonov submitted a review, later dismissed

2022-06-15 09:25 UTC, ssong-iohk requested changes
Can you add the test case (i.e. happy path - the request with filters/sort query parameters)  to [stakePoolHttpProvider.test.ts](https://github.com/input-output-hk/cardano-js-sdk/blob/feature/ADP-1793-Add-stake-pool-order-by-saturation/packages/cardano-services-client/test/StakePoolProvider/stakePoolHttpProvider.test.ts)

2022-06-15 13:31 UTC, lgobbi-atix commented
> Can you add the test case (i.e. happy path - the request with filters/sort query parameters) to [stakePoolHttpProvider.test.ts](https://github.com/input-output-hk/cardano-js-sdk/blob/feature/ADP-1793-Add-stake-pool-order-by-saturation/packages/cardano-services-client/test/StakePoolProvider/stakePoolHttpProvider.test.ts)

The provider interface didn't change. The response for these tests are mocked, it doesn't make sense to add the filters and everything there. Those cases should already be covered with https://github.com/input-output-hk/cardano-js-sdk/pull/270/files#diff-7bf95288ddba72cc435fbe56613884016d332bdba413afd23c5e1e7bcc69ce42R684

2022-06-16 05:44 UTC, rhyslbw commented
> it doesn't make sense to add the filters and everything there

Right, the `HTTPService` implementations are just plumbing, and we could even look at refactoring the base class to be usable without needing to extend.

2022-06-16 11:15 UTC, ssong-iohk reviewed
LGTM for me. 
I will run regression test against `testnet` then approve unless any issues are found. 
And @lgobbi-atix I think you can resolve conflict.

2022-06-16 18:02 UTC, merged