fix: division by zero error at pool rewards query
input-output-hk/cardano-js-sdk pull request #280
Opened 2022-06-13 19:54 UTC by lgobbi-atix

# Context

When stake-pool server is started with testnet-db-snapshot DB then called POST ”stake-pool/search”   with the request - 
```
{ "args":[] }
```
It returns 500 and divide by zero error. 

# Proposed Solution
Add `WHEN COALESCE(stake.active_stake, 0) = 0 THEN 0` check to epoch rewards query

2022-06-14 11:17 UTC, ssong-iohk approved these changes
It works now.
See the successful response. 
[280-response.json.txt](https://github.com/input-output-hk/cardano-js-sdk/files/8899224/280-response.json.txt)

2022-06-14 12:52 UTC, mkazlauskas requested changes
Would be great to have a test that fails without  changes in 1db1b37a4a2e101a07cccd973170c0a3b494b3c5

2022-06-14 14:36 UTC, lgobbi-atix commented
> Would be great to have a test that fails without changes in [1db1b37](https://github.com/input-output-hk/cardano-js-sdk/commit/1db1b37a4a2e101a07cccd973170c0a3b494b3c5)

The test should be this one, which returns all stake pools https://github.com/input-output-hk/cardano-js-sdk/blob/master/packages/cardano-services/test/StakePool/StakePoolHttpService.test.ts#L96

Or even this one https://github.com/input-output-hk/cardano-js-sdk/blob/master/packages/cardano-services/test/StakePool/DbSyncStakePoolProvider/StakePoolBuilder.test.ts#L48 but with a stake pool id with 0 total stake.

Right now we don't have any cases like that in the fixture data, that's why it was not failing before. 
With the way we are currently handling the fixture data adding a case like that it's not easy without hardcoding it

2022-06-15 04:04 UTC, rhyslbw approved these changes

2022-06-16 08:31 UTC, merged