feat: Enhance InMemoryCache 'get' method
input-output-hk/cardano-js-sdk pull request #286
Opened 2022-06-15 08:56 UTC by IvayloAndonov

# Context

In case when the cache is cleared and multiple simultaneous requests come in, we would run the DB query multiple times.
Raised by @mkazlauskas 

# Proposed Solution

Caching the promise instead of resolving the value, so the next invocation will instantly return the same promise.
In case of DB query fails -> `result.catch()` resets the cache so don't have to wait for the TTL

# Important Changes Introduced

2022-06-15 09:00 UTC, rhyslbw requested changes
It would be best to have a test demonstrate this

2022-06-15 09:52 UTC, rhyslbw requested changes
What about the test scenario of multiple requests being received before the cache is primed?

2022-06-15 09:52 UTC, rhyslbw commented on packages/cardano-services/src/InMemoryCache/InMemoryCache.ts
> +    const result = dbSyncQuery();
```suggestion
    const resultPromise = dbSyncQuery();
```

2022-06-15 12:15 UTC, IvayloAndonov commented on packages/cardano-services/src/InMemoryCache/InMemoryCache.ts
> +    const result = dbSyncQuery();
[52a24a2](https://github.com/input-output-hk/cardano-js-sdk/pull/286/commits/52a24a29a6bc040355e2da5a676a9096e50fe987)

2022-06-15 12:45 UTC, mkazlauskas approved these changes
Looks good! The only improvement that comes to mind is a test that `.catch` resets cache, but I think it's good enough as-is.

Also, `perf` seems like a good commit type for this

2022-06-15 13:00 UTC, IvayloAndonov commented
> Looks good! The only improvement that comes to mind is a test that `.catch` resets cache, but I think it's good enough as-is.
> 
> Also, `perf` seems like a better commit type for this

Yeah, I'll squash the commits as `perf` once I've got another approval and its ready for merge

2022-06-17 05:44 UTC, rhyslbw submitted a review, later dismissed

2022-06-17 06:15 UTC, mkazlauskas approved these changes

2022-06-17 06:33 UTC, merged