chore: add Docker Compose file and update DB dump script and process
input-output-hk/cardano-js-sdk pull request #294
Opened 2022-06-21 04:24 UTC by rhyslbw

# Context
We're missing a Docker Compose stack to run the `cardano-services` service dependencies, and it's awkward to create a test DB snapshot.

# Proposed Solution
- Add a Docker Compose file with service dependencies defined
- Update the DB dump script to make it configurable (this is quite basic, and there's likely room for improvement)
- Add an npm script to start an ephemeral container to create the snapshot, overwriting the current.
  
# Important Changes Introduced
- Also added block `3556390` to include on-chain data that includes asset metadata.

2022-06-22 12:28 UTC, ssong-iohk requested changes

2022-06-22 12:52 UTC, rhyslbw commented on packages/cardano-services/docker-compose.yml
> +        "--config", "/config/cardano-db-sync/config.json",
It must be an issue with the config mount, as this path is correct. See the [volume mapping](https://github.com/input-output-hk/cardano-js-sdk/pull/294/files#diff-a5f22c45d19dce606e9bae0a8cd3a11ce586442845b16c7e1a056ac7e028ea79R59) into the root

Maybe you don't have the submodule?

2022-06-22 13:02 UTC, ssong-iohk commented on packages/cardano-services/docker-compose.yml
> +        "--config", "/config/cardano-db-sync/config.json",
Ah. you right. I updated `git submodule` after seeing the error. my bad!

2022-06-22 13:03 UTC, ssong-iohk approved these changes
Thanks @rhyslbw it's handy one.

2022-06-23 14:41 UTC, mkazlauskas submitted a review, later dismissed
LGTM! :rocket:

2022-07-06 04:15 UTC, AngelCastilloB approved these changes
Looks good :)

2022-07-06 04:37 UTC, merged