feat: add missing transaction fields
input-output-hk/cardano-js-sdk pull request #324
Opened 2022-07-11 19:19 UTC by lgobbi-atix

# Context

Some transaction body fields have not yet been defined in our[ core type](https://github.com/input-output-hk/cardano-js-sdk/blob/6431f57ee5d0624784e9ae6c6b6a73b35a514ee0/packages/core/src/Cardano/types/Transaction.ts#L37-L48), so the task here is to complete the mapping to all available properties of the current era (Babbage is out of scope, as it requires the unreleased v11 of the CSL)

Add support for those fields we're missing in [createTransactionInternals](https://github.com/input-output-hk/cardano-js-sdk/blob/master/packages/wallet/src/Transaction/createTransactionInternals.ts), [cslToCore](https://github.com/input-output-hk/cardano-js-sdk/blob/master/packages/core/src/CSL/cslToCore/cslToCore.ts), [coreToCsl](https://github.com/input-output-hk/cardano-js-sdk/tree/master/packages/core/src/CSL/coreToCsl), [finalizeTx](https://github.com/input-output-hk/cardano-js-sdk/blob/6431f57ee5d0624784e9ae6c6b6a73b35a514ee0/packages/wallet/src/SingleAddressWallet.ts#L329-L361):

- collaterals
- mint
- requiredExtraSignatures
- scriptIntegrityHash
- witness

# Proposed Solution
- Add missing fields to `CreateTxInternalsProps` and `InitializeTxProps`
- Add missing fields to `createTransactionInternals`, `initializeTx` and `finalizeTx`
- Modify tests to include the new fields

2022-07-12 04:23 UTC, rhyslbw requested changes
Thanks @lgobbi-atix

The commit can be scope to `wallet`, which I'll do if we get approval from other reviewers.

2022-07-12 04:51 UTC, rhyslbw approved these changes

2022-07-12 14:02 UTC, ssong-iohk approved these changes

2022-07-12 15:00 UTC, ssong-iohk approved these changes

2022-07-13 07:13 UTC, mkazlauskas approved these changes

2022-07-13 07:14 UTC, merged