nix/take 3
input-output-hk/cardano-js-sdk pull request #336
Opened 2022-07-15 19:10 UTC by blaggacao

- chore: upgrade to yarn 3
- chore: add missing dependencies
- chore: bump backoff-rxjs for rxjs 7 compatibility
- chore: bump jest and ts-jest, fix package devDeps
- chore: bump express-openapi-validator to remove vulnerable package dicer as sub-dependency
- chore: bump pouchdb to remove vulnerable node-fetch package sub-dependency
- chore: just run `yarn`
- init: yarn-plugin-nixify

2022-07-19 13:13 UTC, rhyslbw requested changes
Nice work @blaggacao and @YorikSar 🤝 

We're using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/), so when it comes time to squash to a single commit, please use a prefix of `build:`.

2022-07-19 13:24 UTC, mkazlauskas reviewed
Looks good! yarn plugin made it much cleaner :sunglasses:

Just need to squash into `build:` commit as @rhyslbw mentioned

~~Also a question: do we need to commit .yarn/plugins/yarn-plugin-nixify.cjs since it's location is specified in .yarnrc?~~

2022-07-19 13:27 UTC, YorikSar commented
@mkazlauskas I don't really know what is the established way for Yarn plugins, but I would prefer to have it in repo to not depend on external systems during build and development.

2022-07-20 02:42 UTC, rhyslbw approved these changes

2022-07-20 05:21 UTC, mkazlauskas approved these changes

2022-07-20 07:11 UTC, merged