Refacter/adp 1933 make logger a required dependendcy
input-output-hk/cardano-js-sdk pull request #378
Opened 2022-08-05 13:20 UTC by iccicci

# Context

Sometimes it is hard to investigate the source of problems due to lack of logs.

# Proposed Solution

- To make `logger` a required parameter/dependency for all the packages.
- Removed any reference to `dummyLogger` from the `src` directory of each package.

# Important Changes Introduced

Many interface signatures was impacted.

2022-08-05 14:38 UTC, mkazlauskas approved these changes
Nice work! :rocket:

2022-08-08 05:01 UTC, rhyslbw requested changes
The change to `golden-test-generator` actually introduces `bunyan`, and there are also some `console.log` statements still in the code, so it's a distinct change better committed separately as a scoped refactor.

It would also be better to squash all the `*logger is now required` commits into one, as this is a single change we're making against the codebase in one step.

2022-08-08 06:06 UTC, rhyslbw approved these changes
:rocket:

2022-08-08 06:10 UTC, mkazlauskas approved these changes

2022-08-08 06:22 UTC, merged