feat: Manage runnable dependencies by HTTP server and improve DB health check
input-output-hk/cardano-js-sdk pull request #484
Opened 2022-10-12 10:20 UTC by IvayloAndonov

# Context

Our [current DB health check](https://github.com/input-output-hk/cardano-js-sdk/blob/841cf75d346402028b778e03d2ddb6bcd6a45b1e/packages/cardano-services/src/DbSyncProvider.ts#L4) does not take domain rules into consideration that can infer the health of `cardano-db-sync` :
`const HEALTH_CHECK_QUERY = 'SELECT 1';`

Also currently each provider handles and manages the lifecycle methods of its dependencies, in most cases we us on and the same instance of dependency (memoized), ex. Cardano node dependency now becomes a dependency of all DbSync providers, the same as DB .

Ideally, we would have one single place (HttpServer) to instantiate all runnable dependencies and manage them through lifecycle methods.

# Proposed Solution
**Refactoring**:
- move RunnableModule class out of `cardano-services` package to commonplace ( util package is a good option) and reuse it by multiple packages where is needed
- refactor OgmiosCardanoNode to extend RunnableModule as a runnable dependency of HttpServer
- extend HttpServerDependencies with runnableDependencies list to enable HttpServer to manage   runnable common dependencies across services in one single place through lifecycle methods (initialize, start , shutdown etc.)

**HealthCheck improvement**:

- Add CardanoNode as a dependency in DbSyncProvider
- Consider the impact of all providers now being dependent on CardanoNode (Ogmios)
- Compose the health check result based on the following:
1. query `db-sync` for the latest block height (number)
2. call `stateQueryClient.blockHeight()` to get the last block height from the node
3. compare the results with tolerance of 5 blocks behind (db-sync could be out of sync slightly)

# Important Changes Introduced

2022-10-14 05:55 UTC, rhyslbw requested changes
Nice work @IvayloAndonov. Just some minor suggestions

2022-10-14 06:16 UTC, mkazlauskas approved these changes
Nice work!

2022-10-14 06:48 UTC, IvayloAndonov commented on packages/cardano-services/src/Program/utils.ts
> +export const cardanoNodeDependantServices = new Set([
Yeah, only the `TxSubmitHttpService` is not currently in that list, as the current implementation, it has two providers [modes](https://github.com/input-output-hk/cardano-js-sdk/blob/daeb139e9caab35707a3282443566b64324ee94d/packages/cardano-services/src/Program/loadHttpServer.ts#L161-L166): without and with the queue.
The first one ([ogmiosTxSubmitProvider](https://github.com/input-output-hk/cardano-js-sdk/blob/9298ee0e6c98bef0c1aa4dc70f349094ec00a5c9/packages/ogmios/src/Provider/TxSubmitProvider/ogmiosTxSubmitProvider.ts#L23-L43)) depends on ogmios but does not depend on `db-sync`.
The second one ([RabbitMqTxSubmitProvider](https://github.com/input-output-hk/cardano-js-sdk/blob/a1d07549e7a5fccd36b9f75b9f713c0def8cb97f/packages/cardano-services/src/TxSubmit/rabbitmq/RabbitMqTxSubmitProvider.ts#L40-L154)) depends only on `rabbitmq`,
that's why this service is the only exception at the moment, we could think if it needs to be extended somehow.

2022-10-14 09:00 UTC, iccicci approved these changes
I see several improvements in this PR.
GJ!

2022-10-14 09:05 UTC, IvayloAndonov commented on packages/cardano-services/src/Http/HttpServer.ts
> +      this.logger.debug(`Runnable dependency ${dependency.name} has been initialized.`);
a29e6f3a47c9b7df8d9588ffec712529883f55d0

2022-10-14 09:05 UTC, IvayloAndonov commented on packages/cardano-services/src/Http/HttpServer.ts
> +      this.logger.debug(`Service ${service.name} has been shutdown.`);
a29e6f3a47c9b7df8d9588ffec712529883f55d0

2022-10-14 09:05 UTC, IvayloAndonov commented on packages/cardano-services/src/Http/HttpServer.ts
> +      this.logger.debug(`Runnable dependency ${dependency.name} has been shutdown.`);
a29e6f3a47c9b7df8d9588ffec712529883f55d0

2022-10-14 09:07 UTC, IvayloAndonov commented on packages/cardano-services/src/Program/services/ogmios.ts
> -export const getOgmiosCardanoNode = memoize(
Memoize no longer needed

2022-10-14 09:18 UTC, IvayloAndonov commented on packages/cardano-services/test/Program/services/postgres.test.ts
> +        ) as unknown as OgmiosCardanoNode;
This way of mocking will prepare our unit/integration tests when we no longer rely on test fixtures data, but work with local data generated by local-network e2e tests. It handles the introduced relationship between `db-sync` and `cardanoNode` related to the service's health check. (db sync should be synced with the node to determine healthiness)

2022-10-14 09:25 UTC, rhyslbw commented on packages/cardano-services/src/Program/utils.ts
> +export const cardanoNodeDependantServices = new Set([
Ah yes. I'm thinking about generic HTTP providers, which probably all should have a dependency on the local node, even if it's just for clients to perform consistency checks. It's out of scope for this PR though, so I'm happy with it as-is

2022-10-14 09:26 UTC, rhyslbw approved these changes

2022-10-14 14:10 UTC, IvayloAndonov commented
Commits are squashed, CI build passed, and ready for merge once passed again.

2022-10-14 15:46 UTC, iccicci approved these changes

2022-10-18 06:21 UTC, mkazlauskas approved these changes

2022-10-18 08:43 UTC, rhyslbw approved these changes

2022-10-18 08:43 UTC, merged