fix(e2e): updated .env.local-network
input-output-hk/cardano-js-sdk pull request #486
Opened 2022-10-17 13:36 UTC by iadmytro

updated .env.local-network

2022-10-17 13:44 UTC, iccicci submitted a review, later dismissed
Thank you

2022-10-19 05:39 UTC, mkazlauskas approved these changes

2022-10-19 05:43 UTC, mkazlauskas requested changes
Please change the commit type to `chore:`. `fix:` shows up in the changelog and should be reserved for code changes.

2022-10-19 12:54 UTC, mkazlauskas approved these changes

2022-10-19 13:03 UTC, rhyslbw approved these changes
Thanks @iadmytro

2022-10-19 13:03 UTC, merged