ADP-1858-upgrade-from-csl-to-cml
input-output-hk/cardano-js-sdk pull request #495
Opened 2022-10-27 06:54 UTC by AngelCastilloB

# Context

The CSL was compiled to WASM using an old version of rustwasm which had a [bug](https://github.com/rustwasm/wasm-bindgen/issues/1963) that would leak stack space when errors were thrown by the underlying rust library, This was making the CSL WASM module to crash after a several errors were thrown, this was fixed in later versions. The CML library uses the updated rustwasm and as such doesnt have this bug.

# Proposed Solution

Reemplace the CSL library with the CML library

2022-10-27 06:59 UTC, rhyslbw requested changes
I had a heart-in-mouth moment :laughing::
![image](https://user-images.githubusercontent.com/303881/198212974-de64cc87-9bb0-42f6-b2fd-f28430bcd43f.png)

Did you run `npm i`? Please ensure `yarn install` has been run again after removing the `package-lock.json`

2022-10-27 07:07 UTC, mkazlauskas requested changes

2022-10-27 07:07 UTC, mkazlauskas commented on packages/input-selection/src/selectionConstraints.ts
> +      // TODO: Get this from cardano-services
Just flagging this to be resolved

2022-10-27 07:07 UTC, mkazlauskas commented on packages/wallet/test/hardware/LedgerKeyAgent.test.ts
> +    let deviceConnection: any;
Let's try to figure out why this is needed

2022-10-27 15:42 UTC, rhyslbw requested changes
The complete diff looks good, but there's a few distinct changes that have been lumped into a single commit, that need to be separated. I've commented on the ones that stick out to me, but it also appears that we missed including some CSL objects in the managed scope the first time around, so they would be best committed first as `fix`, then the lib replacement can be clean. If the new lib introduces new objects, then that's naturally part of the refactor commit.

2022-10-27 15:42 UTC, rhyslbw commented on packages/e2e/package.json
> +    "@cardano-foundation/ledgerjs-hw-app-cardano": "^5.0.0",
This should be a separate `chore` commit

2022-10-27 15:42 UTC, rhyslbw commented on packages/e2e/src/factories.ts
> +        deviceConnection: null,
Separate `test` commit. Was this a bug?

2022-10-27 15:42 UTC, rhyslbw commented on packages/e2e/test/web-extension/wdio.conf.js
> +        waitforTimeout: 30000
This doesn't belong in the same commit as the CML replacement

2022-10-28 04:45 UTC, rhyslbw commented on packages/e2e/test/web-extension/wdio.conf.js
> +        waitforTimeout: 30000
The commit message is missing some context and includes redundant information already expressed in the diff. Please have another go at this commit message, with an explanation of why this is needed.

2022-10-28 04:46 UTC, rhyslbw requested changes
![image](https://user-images.githubusercontent.com/303881/198504627-449781e7-1ed7-477a-9949-031e280fd430.png)

Some Spanglish? :smile: 

reemplaced -> replaced

2022-10-28 04:49 UTC, rhyslbw commented
> I split the extra manage here: https://github.com/input-output-hk/cardano-js-sdk/commit/b01944c20e258097ad4e08db12e7492e99502482

Great, that's good to see there was only a small number missed in the original implementation

2022-10-28 05:11 UTC, mkazlauskas commented on packages/input-selection/src/selectionConstraints.ts
> +      // TODO: Get this from cardano-services
Are we planning to do this TODO in a separate PR?

2022-10-28 05:12 UTC, mkazlauskas approved these changes
Nice work!

2022-10-28 08:16 UTC, rhyslbw approved these changes
Great work @AngelCastilloB :construction_worker:

2022-10-28 08:18 UTC, mkazlauskas approved these changes

2022-10-28 08:19 UTC, merged