ci: replace workflow cancellation plugin with 'exit 1'
input-output-hk/cardano-js-sdk pull request #505
Opened 2022-11-03 14:38 UTC by mkazlauskas

# Context

Cancelled nightly workflows have 'succeeded' status. This will make it to attempt to publish the packages if the merge fails.

# Proposed Solution

Replace cancellation plugin with `exit 1`

2022-11-04 05:01 UTC, rhyslbw requested changes
Looks good. It's also better to not be dependent on a deprecated action :wink: 
![image](https://user-images.githubusercontent.com/303881/199891510-63c49da4-0bf9-4a88-8516-35606370932c.png)

2022-11-04 05:01 UTC, rhyslbw commented on .github/workflows/nightly-test.yaml
> +    name: "Cancel the workflow run by failing"
```suggestion
    name: "Fail the workflow run by exiting"
```

2022-11-04 06:16 UTC, mkazlauskas commented on .github/workflows/nightly-publish.yaml
> +    name: "Cancel the workflow run by failing"
The intent is to cancel though: publish doesn't fail, we just don't want to do it if this runs

2022-11-04 09:03 UTC, rhyslbw approved these changes

2022-11-07 07:34 UTC, rhyslbw approved these changes

2022-11-07 07:48 UTC, merged