test(e2e): load test improvements
input-output-hk/cardano-js-sdk pull request #506
Opened 2022-11-03 15:40 UTC by iccicci

# Context

Looking for a good test to stress the transaction submission, we found that the tx submissions load test could be a good candidate, but it needs some fixes/improvements.

# Important Changes Introduced

- removed the `try/catch` block around the body of the test which was hiding test failures
- coins are now self sent to the same account to avoid the too many inputs error in subsequent test runs (with high `TRANSACTIONS_NUMBER`)

2022-11-07 06:38 UTC, mkazlauskas approved these changes
Looks good! :rocket:

2022-11-07 07:32 UTC, rhyslbw requested changes
Looks good @iccicci. Please add the description you left here to the commit message, as it's important context to be included in the log, and not just here in a GitHub feature.

2022-11-07 12:16 UTC, iadmytro commented
It would be good to add example .env file for this test

2022-11-09 13:34 UTC, rhyslbw approved these changes
Nice work @iccicci :sunflower:

2022-11-11 05:30 UTC, merged