Feat/rename era specific types
input-output-hk/cardano-js-sdk pull request #542
Opened 2022-11-28 22:56 UTC by IvayloAndonov

# Context

Cardano.TxAlonzo → Cardano.Tx, NewTxAlonzo → NewTx, TxBodyAlonzo → TxBody

# Proposed Solution

# Important Changes Introduced

2022-11-29 07:43 UTC, rhyslbw requested changes
Looks good @IvayloAndonov, but the change is breaking, so need the correct annotation in the commit message.

2022-11-29 07:46 UTC, mkazlauskas reviewed
Looks good! Although now I'm thinking that since we're changing this, might as well consider:
- `NewTx` -> `Tx`, as this type is aligned with ledger type
- `Tx` -> `ExtendedTx?`, not sure about the name, but this type has some extra properties that ChainHistoryProvider resolves (notably `address` on `TxIn`), but is not present in serialized types.

Thoughts @rhyslbw ?

2022-11-29 07:49 UTC, rhyslbw commented
> Tx -> ExtendedTx?, not sure about the name, but this type has some extra properties that ChainHistoryProvider resolves (notably address on TxIn), but is not present in serialized types.

`HydratedTx` ?

2022-11-29 11:52 UTC, IvayloAndonov commented
All naming suggestions are applied with the fixups, ready for review @rhyslbw @mkazlauskas

2022-11-29 12:13 UTC, mkazlauskas approved these changes
Good to squash!

2022-11-30 11:02 UTC, rhyslbw approved these changes

2022-11-30 11:02 UTC, merged