fix(input-selection): fixed recursive use of CSL object
input-output-hk/cardano-js-sdk pull request #549
Opened 2022-11-30 16:55 UTC by AngelCastilloB

# Context

1. The CML WASM module is throwing "Error: recursive use of an object detected which would lead to unsafe aliasing in rust", This can happen when two segments of code try to borrow the same object.
The function that is throwing is using a constant which is a CML object of type BigNum, this object is then reused everytime the function is called.
2. We suspect that asm.js variant of CML is sometimes going out of memory.

# Proposed Solution

1. Create a new managed BigNum on every call and pass it to the Rust function.
2. Update test extension to use WASM variant of CML. As a positive consequence we managed to reduce bundle sizes by allowing webpack to do tree-shaking.

2022-12-01 03:57 UTC, rhyslbw requested changes
Good catch @AngelCastilloB. Can you add a test to cover the bug being fixed? Also, I wonder if there are other cases of this bug. Have you done a more widespread review?

2022-12-01 04:09 UTC, rhyslbw requested changes
How about converting the `cmlUtil.maxBigNum` into a function instead (which makes it a real utility)? It would need the scope passed in.

2022-12-02 07:01 UTC, rhyslbw requested changes

2022-12-02 07:01 UTC, rhyslbw commented on packages/wallet/test/SingleAddressWallet/load.test.ts
> +const getAssets = (utxos: Cardano.Utxo[]) => {
```suggestion
const getAssetsFromUtxos = (utxos: Cardano.Utxo[]) => {
```

Better if this was sourced in the `util` package

2022-12-02 07:30 UTC, rhyslbw commented on packages/wallet/test/SingleAddressWallet/load.test.ts
> +const getAssets = (utxos: Cardano.Utxo[]) => {
This is actually not possible due to the current dependency `core` has on `util`, so disregard this suggestion. We can look at hoisting when the opportunity arises.

2022-12-02 12:17 UTC, rhyslbw submitted a review, later dismissed

2022-12-02 12:30 UTC, mkazlauskas submitted a review, later dismissed
Nice work!

2022-12-05 13:40 UTC, mkazlauskas approved these changes

2022-12-05 13:47 UTC, merged