feat: added new babbage era types in Transactions and Outputs
input-output-hk/cardano-js-sdk pull request #563
Opened 2022-12-13 05:41 UTC by AngelCastilloB

# Context

To support the new Babbage Era features, we must:

- Add the new fields (e.g. collateral return, inline datums, etc.) to the Core package’s types.
- Ensure serialization of those new fields is possible & well tested
- Including all existing Alonzo fields that have not yet been added.

# Proposed Solution

Add the new Babbage types to our core types.

# Important Changes Introduced

New fields of transaction body include:

1. collateral return;
2. total collateral
3. reference inputs;

New fields of transaction outputs include:

1. inline datum   
2. script referen

2022-12-13 13:54 UTC, mkazlauskas requested changes

2022-12-13 13:54 UTC, mkazlauskas commented on packages/core/src/Cardano/types/Utxo.ts
> -  datum?: Hash32ByteBase16;
This makes it a breaking change: please update commit msg

2022-12-13 13:54 UTC, mkazlauskas commented on packages/core/src/Cardano/types/Utxo.ts
> +   * users consume this output without specifying the datum value.
They are still specifying the datum value, but they can find it on-chain.
```suggestion
   * users consume this output without specifying the datum value separately.
```

2022-12-13 13:54 UTC, mkazlauskas commented on packages/core/src/Cardano/types/Utxo.ts
> +   * transaction to do so. This will allow transactions using common scripts to be much smaller.
```suggestion
   * transaction to do so. This allows transactions using common scripts to be much smaller.
```

2022-12-13 13:54 UTC, mkazlauskas commented on packages/core/src/Cardano/types/Utxo.ts
> +  scriptRef?: Script;
This should probably be a different type
```suggestion
  scriptRef?: ScriptReference;
```

2022-12-13 13:54 UTC, mkazlauskas commented on packages/ogmios/src/ogmiosToCore/tx.ts
> +  if (typeof datum === 'object') return Cardano.util.HexBlob(JSON.stringify(datum));
Is this correct? :thinking: Need a test with ogmios inline datum

2022-12-13 16:13 UTC, mkazlauskas commented on packages/core/src/Cardano/types/Utxo.ts
> +   * users consume this output without specifying the datum value.
Right, you only specify `{txId,index}`

2022-12-15 11:57 UTC, mkazlauskas commented on packages/core/src/Cardano/types/Utxo.ts
> +  scriptRef?: Script;
Oh so it's actually the 'Script' type. Maybe let's go back to using the existing `Script` type then, but also rename the field? Like this:
```ts
script: Script
```
Then, how is it actually referenced (used as witness)?

2022-12-15 12:01 UTC, mkazlauskas commented on packages/ogmios/src/ogmiosToCore/tx.ts
> +  if (typeof datum === 'object') return Cardano.util.HexBlob(JSON.stringify(datum));
Do we have test data when ogmios datum is an `object`?

2022-12-15 14:17 UTC, mkazlauskas commented on packages/core/src/Cardano/types/Utxo.ts
> +  scriptRef?: Script;
> but if we want to change it to just script I am also okay with that

I can't think of a reason to have a separate type if it refers to the same thing, so yeah, let's do that unless there's a reason to have separate types.

> ...as a reference input and the node will search for the eUTXO and fetch the script automatically. What I have done here allows us to create these reference outputs (or inputs), but we are still missing the part of using them, that will come once we have smart-contract support

Thanks for an explanation. The part of using them is what's unclear to me, are all scripts in reference inputs implicitly used as witness? :thinking:

2022-12-15 14:19 UTC, mkazlauskas commented on packages/ogmios/src/ogmiosToCore/tx.ts
> +  if (typeof datum === 'object') return Cardano.util.HexBlob(JSON.stringify(datum));
Maybe it's only relevant for `datum_hash`: https://github.com/CardanoSolutions/ogmios/blob/master/clients/TypeScript/packages/schema/src/index.ts#L1120

My guess is that key = scripthash and value=datumhash there

2022-12-15 14:25 UTC, mkazlauskas commented on packages/ogmios/src/ogmiosToCore/tx.ts
> +  if (typeof datum === 'object') return Cardano.util.HexBlob(JSON.stringify(datum));
I think our current implementation is incorrect. Key and value there needs to be interpreted separately:
- key=hash32 (script hash? not sure)
- value=plutus_data (the hexblob)

https://github.com/input-output-hk/cardano-ledger/blob/master/eras/babbage/test-suite/cddl-files/babbage.cddl#L421

Let's try to figure out what is the difference between 'Datum' and key-value object: https://github.com/CardanoSolutions/ogmios/blob/master/clients/TypeScript/packages/schema/src/index.ts#L1120-L1123

2022-12-15 14:40 UTC, mkazlauskas commented on packages/ogmios/src/ogmiosToCore/tx.ts
> +  if (typeof datum === 'object') return Cardano.util.HexBlob(JSON.stringify(datum));
In that case we should drop the key and only use the value?

Or can a single output have multiple datums? :thinking: In this case we'd need to update our core type

2022-12-16 14:24 UTC, mkazlauskas requested changes

2022-12-16 14:24 UTC, mkazlauskas commented on packages/ogmios/src/ogmiosToCore/tx.ts
> +  if (!datum || typeof datum !== 'string') return;
Can there be an empty datum string? Either way, I think `typeof` should be sufficient here.
```suggestion
  if (typeof datum !== 'string') return;
```

2022-12-20 14:33 UTC, mkazlauskas approved these changes
Nice work! Great to see extensive doc comments :muscle:

2022-12-20 14:39 UTC, IvayloAndonov submitted a review, later dismissed
Great work!🔝

2022-12-21 14:27 UTC, mkazlauskas approved these changes

2022-12-22 07:31 UTC, IvayloAndonov approved these changes

2022-12-22 07:34 UTC, merged