Feat/adp 2534 replace current fee calculation
input-output-hk/cardano-js-sdk pull request #582
Opened 2023-01-22 16:50 UTC by AngelCastilloB

# Context

We want to remove the dependency on the CML/CSL from the SDK, part of the functionality we are using from these libraries is related to TX min fee calculation. In particular two functions:

- Minimum Ada Required.
- Min Fee.

# Proposed Solution

Implement these two functions natively in the SDK.

# Important Changes Introduced

The minimum ADA required (per UTXO) and min fee is now calculated natively by the SDK.

2023-01-26 08:11 UTC, mkazlauskas requested changes

2023-01-26 08:11 UTC, mkazlauskas commented on packages/input-selection/src/selectionConstraints.ts
> +    const prices = { memory: 0.0577, steps: 0.000_007_21 };
You can extend `ProtocolParametersRequiredByInputSelection` to get the `prices`

2023-01-26 08:11 UTC, mkazlauskas commented on packages/input-selection/test/testData.ts
> +      txId: Cardano.TransactionId(getRandomHash(64))
from `util-dev`
```suggestion
      txId: generateRandomHexString(64)
```

2023-01-26 08:11 UTC, mkazlauskas commented on packages/input-selection/test/fees.test.ts
> +    it('calculate the correct min fee for a babbage transaction', () => {
```suggestion
    it('calculate the correct min fee for transaction without scripts', () => {
    it('calculate the correct min fee for transaction with scripts', () => {
```

2023-01-31 07:09 UTC, mkazlauskas commented on packages/input-selection/src/fees.ts
> +  const totalExUnits = getTotalExUnits(tx.witness.redeemers);
Thanks @AngelCastilloB

2023-01-31 07:13 UTC, mkazlauskas approved these changes
Nice work!

2023-01-31 07:13 UTC, mkazlauskas commented on packages/input-selection/test/fees.test.ts
> +      expect(fee).toBe(206_905n);
Isn't this a little too high? I remember seeing fees at around .17

2023-01-31 09:22 UTC, rhyslbw reviewed
We have a bit of scope creep here introducing fee calculation. Thinking ahead to offering a library that handles lower level transaction construction, that `wallet` and our future `dapp` (name just a placeholder) package can depend on, how about one of the two options:

- rename `input-selection` to `tx-construction`
- add `tx-construction` with a dependency on `input-selection`, retaining the modularity we already have

2023-02-08 10:57 UTC, mkazlauskas submitted a review, later dismissed
Nice work!

2023-02-08 10:57 UTC, mkazlauskas commented on packages/wallet/test/mocks/mockData.ts
> +  prices: { memory: 0.0577, steps: 0.000_007_21 },
Shouldn't this be in 7f6d706453bed26f318eb5a984c10712d444eef8?

2023-02-08 16:28 UTC, rhyslbw requested changes
Nice work @AngelCastilloB. Just a few spelling typo/mistakes in both commit messages to correct at the last squash

2023-02-08 17:50 UTC, merged