fix(core): omits NFT metadata files with invalid format
input-output-hk/cardano-js-sdk pull request #588
Opened 2023-01-27 10:12 UTC by IvayloAndonov

# Context
Currently, if `metadatum` has missing information which is required based on CIP-25, we return `null` as result. 

# Proposed Solution
- omits NFT metadata files with missing fields (`name`, `src`, `mediaType`) 

# Important Changes Introduced

2023-01-31 06:52 UTC, mkazlauskas requested changes

2023-01-31 06:52 UTC, mkazlauskas commented on packages/core/test/Asset/util/metadatumToCip25.test.ts
> +      const metadatum = fromSerializableObject<Cardano.MetadatumMap>({
Maybe reuse the rest of the metadata object to make the tests a little cleaner
```suggestion
      const metadatum = createMetadatum({ files: [ ... ] })
```

2023-01-31 06:52 UTC, mkazlauskas commented on packages/core/src/Asset/util/metadatumToCip25.ts
> +  `Missing file's ${fieldType} for asset: ${assetId}`;
```suggestion
  `Omitting NFT metadata file: ${fieldType} for asset: ${assetId}`;
```

2023-02-01 11:17 UTC, mkazlauskas commented on packages/core/test/Asset/util/metadatumToCip25.test.ts
> +      const metadatum = fromSerializableObject<Cardano.MetadatumMap>({
4968db203016b9c895cb17f189bca8eb7ef38afa

2023-02-01 11:18 UTC, mkazlauskas commented on packages/core/src/Asset/util/metadatumToCip25.ts
> +  `Missing file's ${fieldType} for asset: ${assetId}`;
f9997b2ad16bec86b903cca4eba4cee13a41801a

2023-02-01 11:24 UTC, rhyslbw requested changes

2023-02-01 11:24 UTC, rhyslbw commented on packages/core/test/Asset/util/metadatumToCip25.test.ts
> +  describe('omits NFT metadata files with invalid format', () => {
```suggestion
  describe('invalid metadata on optional fields', () => {
```

2023-02-01 11:24 UTC, rhyslbw commented on packages/core/test/Asset/util/metadatumToCip25.test.ts
> +    it('missing file name', () => {
```suggestion
    it('omits files with a missing file name', () => {
```

2023-02-01 11:24 UTC, rhyslbw commented on packages/core/test/Asset/util/metadatumToCip25.test.ts
> +    it('missing file media type', () => {
```suggestion
    it('omits files with a missing file media type', () => {
```

2023-02-01 11:24 UTC, rhyslbw commented on packages/core/test/Asset/util/metadatumToCip25.test.ts
> +    it('missing file source', () => {
```suggestion
    it('omits files with a missing file source', () => {
```

2023-02-01 11:29 UTC, mkazlauskas commented on packages/core/test/Asset/util/metadatumToCip25.test.ts
> +  describe('omits NFT metadata files with invalid format', () => {
88320515b1bfa81bd77f4e7d53ee47cc15917f90

2023-02-01 11:29 UTC, mkazlauskas commented on packages/core/test/Asset/util/metadatumToCip25.test.ts
> +    it('missing file name', () => {
88320515b1bfa81bd77f4e7d53ee47cc15917f90

2023-02-01 11:29 UTC, mkazlauskas commented on packages/core/test/Asset/util/metadatumToCip25.test.ts
> +    it('missing file media type', () => {
88320515b1bfa81bd77f4e7d53ee47cc15917f90

2023-02-01 11:30 UTC, mkazlauskas commented on packages/core/test/Asset/util/metadatumToCip25.test.ts
> +    it('missing file source', () => {
88320515b1bfa81bd77f4e7d53ee47cc15917f90

2023-02-01 11:30 UTC, rhyslbw submitted a review, later dismissed
Great work @IvayloAndonov. Thanks for picking it up too @mkazlauskas

2023-02-01 11:34 UTC, mkazlauskas approved these changes

2023-02-01 11:36 UTC, rhyslbw approved these changes

2023-02-02 15:44 UTC, merged