ADP-2574 feat/crypto library interface and key management refactor
input-output-hk/cardano-js-sdk pull request #589
Opened 2023-01-30 23:13 UTC by AngelCastilloB

# Context

We must add an abstraction for the crypto operations for the key management package to depend on, so we can do comparison tests between implementations.

# Proposed Solution

Add an interface and extension point around the cryptographic operations in the SDK.

# Important Changes Introduced

- Added a new interface Crypto package.
- Added a new Ed25519Provider interface to abstract cryptographic operations.
- Added a new Cryptographic provider implemented in terms of the CML library.
- The key-management package was refactored to use the new abstraction.

2023-01-31 08:14 UTC, mkazlauskas requested changes
Please highlight changes to the interface in e1a6b103000d8f0cf0c0fc8e42559279c01f44e6 commit message (new required 'cryptoProvider' property in some types)

2023-01-31 09:02 UTC, rhyslbw requested changes
I'd like to see us avoid overloading the _provider_ term, since it has a specific meaning of establishing query or command access to the blockchain. How about we use the term 'lib' here as a substitute?

2023-02-01 10:27 UTC, rhyslbw commented on packages/crypto/src/Ed25519Provider.ts
> +export interface Ed25519Provider {
This can just be `Bip32Ed25519`

2023-02-01 10:28 UTC, rhyslbw commented on packages/crypto/src/Providers/CmlEd25519Provider.ts
> +export class CmlEd25519Provider implements Ed25519Provider {
`CmlEd25519`

2023-02-01 10:29 UTC, rhyslbw commented
Let's drop `Lib` too, and go with:

- `Bip32Ed25519`
- `CmlBip32Ed25519`
- `SodiumBip32Ed25519`

2023-02-03 09:51 UTC, mkazlauskas commented on packages/crypto/src/Providers/CmlEd25519Provider.ts
> +   * Turns an initial entropy into a secure cryptographic master key.
Yep looks good. I don't think there's any reason to treat strategy module differently though - it can still have  `index.ts`, just not export `CML`

2023-02-03 09:55 UTC, mkazlauskas commented on packages/crypto/test/providers/CmlEd25519Provider.test.ts
> +  const provider = new Crypto.CmlEd25519Provider();
Maybe let's rename the file to just `BipEd25519.test.ts` OR move the reusable tests function to a separate file and import it in `CmlBip32Ed25519.test.ts`

2023-02-03 09:56 UTC, mkazlauskas commented on packages/crypto/src/Providers/CmlEd25519Provider.ts
> +export class CmlEd25519Provider implements Ed25519Provider {
Yep looks good. I don't think there's any reason to treat strategy module differently though - it can still have index.ts, just not export CML

2023-02-03 10:10 UTC, mkazlauskas requested changes

2023-02-03 10:10 UTC, mkazlauskas commented on packages/crypto/package.json
> +  },
Users can use any of those:
```suggestion
  "peerDependencies": {
    "@dcspark/cardano-multiplatform-lib-nodejs": "^3.1.1",
    "@dcspark/cardano-multiplatform-lib-browser": "^3.1.1",
    "@dcspark/cardano-multiplatform-lib-asmjs": "^3.1.1"
  },
  "peerDependenciesMeta": {
    "@dcspark/cardano-multiplatform-lib-nodejs": {
      "optional": true
    },
    "@dcspark/cardano-multiplatform-lib-browser": {
      "optional": true
    },
    "@dcspark/cardano-multiplatform-lib-asmjs": {
      "optional": true
    }
  },
```

2023-02-03 10:10 UTC, mkazlauskas commented on packages/governance/test/cip36.test.ts
> +          const bip32Ed25519 = new Crypto.CmlBip32Ed25519(CML);
:+1:

2023-02-03 15:22 UTC, mkazlauskas submitted a review, later dismissed
Nice work! :rocket:

2023-02-03 16:26 UTC, rhyslbw approved these changes
Awesome work here @AngelCastilloB :star_struck:

2023-02-06 06:41 UTC, mkazlauskas approved these changes

2023-02-06 12:26 UTC, merged