fix(e2e): wallet restoration scenario
input-output-hk/cardano-js-sdk pull request #615
Opened 2023-02-23 17:25 UTC by IvayloAndonov

# Context
I found one issue in debug log severity while performing a bunch of load test executions - the wallet restoration scenario uses one and the same fetched address from DB as the exposed [walletRestoration](https://github.com/input-output-hk/cardano-js-sdk/blob/90de06309ddccd971c8ba5c95e1ee23761891f31/packages/e2e/test/artillery/wallet-restoration/WalletRestoration.ts#L54-L87) function doesn’t iterate over all fetched addresses. 

The issue is caused due to the index variable which tracks the current address from the addresses found list. The walletRestoration function is invoked for each new virtual user, so the index should be located in the global scope rather than the function scope, and then incremented accordingly by each invocation.

# Important Changes Introduced
- fix DB addresses traversing, move current address index to global scope

2023-02-23 18:59 UTC, rhyslbw requested changes
Good work with the fix @IvayloAndonov

2023-02-27 08:23 UTC, IvayloAndonov commented on packages/e2e/test/artillery/wallet-restoration/WalletRestoration.ts
> -    try {
The changes are produced by removing of [this](https://github.com/input-output-hk/cardano-js-sdk/pull/615/files#diff-2d47612f7523cafe3ae2f88f57ab780cf5c6d1ce410c6040d33faf4602418e1bL56) line, so the function scope is different and formatted.

2023-02-27 09:15 UTC, rhyslbw commented on packages/e2e/test/artillery/wallet-restoration/WalletRestoration.ts
> -    try {
Sorry! :face_with_head_bandage:

2023-02-27 09:16 UTC, rhyslbw approved these changes

2023-02-27 11:27 UTC, iccicci approved these changes
Nice!

2023-02-27 14:58 UTC, merged