Fix/asset fingerprint internal impl
input-output-hk/cardano-js-sdk pull request #621
Opened 2023-03-01 13:18 UTC by mirceahasegan

# Context

It is simple enough to implement this in the SDK

2023-03-01 14:15 UTC, rhyslbw requested changes
Looks good @mirceahasegan

2023-03-01 17:19 UTC, mirceahasegan commented on packages/core/test/Cardano/types/Asset.test.ts
>        expect(AssetFingerprint.fromParts(policyId, assetName)).toEqual('asset1rqluyux4nxv6kjashz626c8usp8g88unmqwnyh');
I updated the test name to `creates expected fingerprint from cip14 test vectors` and removed the test that was not part of the test vectors: [4add154](https://github.com/input-output-hk/cardano-js-sdk/pull/621/commits/4add154f36cf2083ae99d4806f2f5f44ecbc6485)

2023-03-02 13:10 UTC, mkazlauskas commented on packages/crypto/src/index.ts
> +export { blake2b };
Let's use that then

2023-03-02 13:12 UTC, mkazlauskas approved these changes
Nice work! :rocket:

2023-03-02 16:16 UTC, rhyslbw requested changes
Looks good @mirceahasegan. Probably better to make [this](https://github.com/input-output-hk/cardano-js-sdk/pull/621/commits/4add154f36cf2083ae99d4806f2f5f44ecbc6485) a refactor type since it's not a bug on our side, and the commit message reads like the former.

2023-03-02 19:31 UTC, rhyslbw requested changes
Just realised the [package is still listed as a dependency](https://github.com/input-output-hk/cardano-js-sdk/blob/276f63deb3ab81e5eeda75877ffbeaa57c94771f/packages/core/package.json#L79)

2023-03-02 20:41 UTC, mirceahasegan commented
> Just realised the [package is still listed as a dependency](https://github.com/input-output-hk/cardano-js-sdk/blob/276f63deb3ab81e5eeda75877ffbeaa57c94771f/packages/core/package.json#L79)

Great catch!

2023-03-02 20:49 UTC, mirceahasegan commented
@rhyslbw , I removed cip-14 package and force pushed

2023-03-03 06:25 UTC, mkazlauskas approved these changes

2023-03-03 09:20 UTC, rhyslbw approved these changes
:tada:

2023-03-03 11:02 UTC, rhyslbw approved these changes

2023-03-03 11:02 UTC, merged