feat(cardano-services): make all services a HTTP microservice for monitoring
input-output-hk/cardano-js-sdk pull request #622
Opened 2023-03-01 15:28 UTC by rhyslbw

# Context
All services need to expose an HTTP server for monitoring, so our current name is too generic.

# Proposed Solution
- Rename the existing `http-server` service to `provider-server`

# Important Changes Introduced

2023-03-02 10:40 UTC, iccicci submitted a review, later dismissed
Great job!

2023-03-02 13:00 UTC, mkazlauskas requested changes
Looking good, but the tests are failing

2023-03-02 14:21 UTC, rhyslbw commented on packages/cardano-services/src/Http/HttpServer.ts
> +    const servicesReadyCheckHandler = async (req: express.Request, res: express.Response) => {
https://github.com/input-output-hk/cardano-js-sdk/pull/622/commits/aca2c40edc3aec2120969c5ca680763c1d8639cf

2023-03-02 15:52 UTC, mkazlauskas submitted a review, later dismissed
Nice work! :rocket:

2023-03-02 15:52 UTC, iccicci submitted a review, later dismissed

2023-03-02 23:21 UTC, iccicci approved these changes
Now I used this, I understood how much powerful it is 🚀

2023-03-03 06:25 UTC, mkazlauskas submitted a review, later dismissed

2023-03-03 09:18 UTC, iccicci approved these changes

2023-03-03 09:44 UTC, merged