refactor!: the TxSubmit endpoint no longer adds the stack trace when …
input-output-hk/cardano-js-sdk pull request #651
Opened 2023-03-16 05:35 UTC by AngelCastilloB

# Context

We need to strip the stack trace from domain error at the HTTP API when running in a production env.

# Proposed Solution
 - Strip the stack trace from domain error at the HTTP API

2023-03-16 08:45 UTC, mkazlauskas commented on packages/ogmios/src/CardanoNode/OgmiosCardanoNode.ts
> +        CardanoNodeUtil.asCardanoNodeError(error) || new CardanoNodeErrors.UnknownCardanoNodeError(error);
Maybe let's keep the stack trace for UnknownCardanoNodeError - it could be useful

2023-03-16 10:19 UTC, mkazlauskas requested changes
If we're stripping stack trace from `systemStart` and `stakeDistribution`, then we should also do it for `eraSummaries`. However I would limit the scope of this task to just stripping the stack trace of `submitTx`.

2023-03-16 10:43 UTC, rhyslbw commented
How about stripping it here: https://github.com/input-output-hk/cardano-js-sdk/blob/87f4160424c0f21a050365af75b0b22056bdb3c2/packages/cardano-services/src/Http/HttpService.ts#L69-L73

It moves the stripping of this server-relevant information in **all** responses from a single point in, arguably, the correct layer; From the HTTP interactions, which is a boundary we're looking to protect. This will result in smaller payloads for all exceptions, and more assurance we're not missing particular cases.

2023-03-17 06:59 UTC, mkazlauskas requested changes

2023-03-17 06:59 UTC, mkazlauskas commented on packages/util/src/errors.ts
> +interface HasInnerErrorLike {
I think that's a little nicer, but feel free to keep the original
```suggestion
interface WithInnerError {
```

2023-03-17 06:59 UTC, mkazlauskas commented on packages/util/src/errors.ts
> +export const stripStackTrace = (error: unknown) => {
Need unit tests since new utils are exported from index

2023-03-17 06:59 UTC, mkazlauskas commented on packages/util/src/environment.ts
> +export const isDevelopmentEnvironment = (): boolean => process.env.NODE_ENV === Environment.Production;
No NODE_ENV is typically interpreted as development. I'd remove the Unknown variant too.
```suggestion
export const isDevelopmentEnvironment = (): boolean => process.env.NODE_ENV !== Environment.Production;
```

2023-03-17 07:34 UTC, mkazlauskas approved these changes
Nice work, no need for fixup for last change request

2023-03-17 07:34 UTC, mkazlauskas commented on packages/util/src/environment.ts
> +  process.env.NODE_ENV ? process.env.NODE_ENV === Environment.Production : false;
```suggestion
  process.env.NODE_ENV === Environment.Production;
```

2023-03-17 08:11 UTC, mirceahasegan submitted a review, later dismissed
Great work, @AngelCastilloB !

2023-03-17 10:38 UTC, rhyslbw submitted a review, later dismissed
Nice work @AngelCastilloB :tada:

2023-03-17 10:54 UTC, mkazlauskas submitted a review, later dismissed

2023-03-17 11:17 UTC, iccicci commented on packages/util/src/errors.ts
> +  error !== undefined && typeof error === 'object' && 'innerError' in (error as never);
```suggestion
  error !== null && typeof error === 'object' && 'innerError' in (error as never);
```
`typeof null === "object"`
while
`typeof undefined === "undefined"`

2023-03-22 15:21 UTC, merged