fix: circular deps check in CI
input-output-hk/cardano-js-sdk pull request #668
Opened 2023-03-23 12:01 UTC by IvayloAndonov

# Context
Currently `circular-deps:check` script does not exit appropriately if there are circular refs in the compiled source code. This is cause by `--summary` flag we use for more structured and beautiful output but it masks the exiting and always exits with `0` which is not documented.

# Proposed Solution

# Important Changes Introduced
- remove `--summary` flag so exit codes are correct
- resolve all circular refs within packages

2023-03-23 12:05 UTC, mkazlauskas approved these changes
Nice work!

2023-03-23 12:05 UTC, mkazlauskas commented on packages/cardano-services/src/Asset/AssetHttpService.ts
> +import { ServiceNames } from '../Program/programs/types';
This appears to be in a wrong file as it's not a type. Not required to resolve to merge this PR

2023-03-23 15:57 UTC, iccicci approved these changes
Very nice!

2023-03-23 19:42 UTC, iccicci requested changes
Better to change `madge --circular dist` to `madge --circular dist/cjs 2> /dev/null`.
`dist` to `dist/cjs` to make it faster;
`2> /dev/null` to produce a more clean output.
This in all `package.json` files

2023-03-24 16:14 UTC, iccicci approved these changes

2023-03-27 12:32 UTC, IvayloAndonov commented
Squashed and ready for merge @mkazlauskas  @iccicci

2023-03-28 06:13 UTC, mkazlauskas approved these changes

2023-03-28 06:13 UTC, merged