feat(cardano-services): add sql script for Provider Server db-sync indexes
input-output-hk/cardano-js-sdk pull request #683
Opened 2023-04-05 10:32 UTC by mkazlauskas

# Context

Deployment needs to source application-specific indexes

# Proposed Solution

Add sql script

2023-04-05 10:35 UTC, rhyslbw requested changes
Let's include db-sync in the file path for distinction:
`packages/cardano-services/config/cardano-db-sync/create-provider-server-indexes.sql`

2023-04-05 10:40 UTC, iccicci approved these changes

2023-04-05 10:41 UTC, rhyslbw approved these changes

2023-04-05 10:45 UTC, rhyslbw requested changes
This should be applied in our Docker instance. One solution is to define a thin wrapper Dockerfile around `inputoutput:cardano-db-sync`, with a custom entrypoint.

2023-04-05 10:53 UTC, rhyslbw approved these changes

2023-08-10 11:58 UTC, mkazlauskas commented
Closing this as we're currently focused on setting up typeorm services instead of improving the setup of db-sync

2023-08-10 11:58 UTC, closed without merging