Feat/adp 2802 implement serialization of tx main body
input-output-hk/cardano-js-sdk pull request #693
Opened 2023-04-12 12:14 UTC by AngelCastilloB

# Context

We want to remove the dependency of the SDK with the CML library. For this we need to develop our own serialization logic around the Cardano domain types.

# Proposed Solution

- Implement a set of CBOR classes that follow the Reader/Writer pattern. These classes will allow us to be very precise and control how the types are serialized. This will also allow us to solve the round trip problem we currently have due difference on transactions generated by the CLI or the CSL/CML library.

- Create a Transaction class which can serialize and serialize to CBOR format. This class must also be able to convert to and from Core.Tx type

# Important Changes Introduced

- Removed the dependency on borc library.
- CborReader and CborWriter introduced.

2023-04-13 05:29 UTC, mkazlauskas requested changes

2023-04-13 05:29 UTC, mkazlauskas commented on packages/cardano-services/src/TxSubmit/rabbitmq/TxSubmitWorker.ts
> +      txId = (await cmlUtil.deserializeTx(txBody)).id;
Just noticed that we have a more efficient way to do this:
```suggestion
      txId = TransactionId.fromTxBodyCbor(TxBodyCBOR.fromTxCBOR(txBody))
```
Maybe we can also update those utils to (at least partially) use new serialization?

2023-04-18 04:52 UTC, mkazlauskas submitted a review, later dismissed
Great work @AngelCastilloB! :rocket:

2023-04-21 13:48 UTC, mirceahasegan commented
This commit is not verified: [64513af](https://github.com/input-output-hk/cardano-js-sdk/pull/693/commits/64513af48c8a30e055c6fe83a45babf69a10532f)

2023-04-24 08:12 UTC, mirceahasegan approved these changes
Fantastic work, @AngelCastilloB :mage_man:

2023-04-27 08:25 UTC, mkazlauskas approved these changes
:rocket:

2023-04-27 08:27 UTC, rhyslbw approved these changes
Great work @AngelCastilloB :mechanical_arm:

2023-04-27 08:27 UTC, merged