fix: the transaction id computation now accounts for serialization round trip errors
input-output-hk/cardano-js-sdk pull request #771
Opened 2023-06-19 03:49 UTC by AngelCastilloB

# Context

Because of how CBOR works. There are multiple ways in CBOR to represent the same data. Unfortunately right now the CML  doesn't maintain the serialization format upon using from_bytes so if cardano-cli uses non-canonical CBOR this will result in different hashes.

# Proposed Solution

Maintain the original the serialized bytes of the body, and use that to compute the hash instead of re serializing (when possible).

# Important Changes Introduced

Added a new method to the transaction class 'getId' which always compute the hash of the transaction body using the original bytes found in the transaction (if available). Please note that if changes to the transaction body are made, this cache will be invalidated.

2023-06-19 11:00 UTC, rhyslbw requested changes

2023-06-19 11:00 UTC, rhyslbw commented on packages/core/test/Serialization/Transaction.test.ts
> +  it('can compute the right TX Id', () => {
```suggestion
  it('can compute the right Tx ID', () => {
```

2023-06-19 11:00 UTC, rhyslbw commented on packages/core/test/Serialization/Transaction.test.ts
> +    // If we can compute the right TX Id it means we are handling the round trip difference correctly.
```suggestion
    // If we can compute the right Tx ID it means we are handling the round trip difference correctly.
```

2023-06-19 11:00 UTC, rhyslbw commented on packages/core/test/Serialization/Transaction.test.ts
> +      '2d7f290c815e061fb7c27e91d2a898bd7b454a71c9b7a26660e2257ac31ebe32'
Please add a comment here to explain how this value can be verified

2023-06-20 10:33 UTC, rhyslbw approved these changes

2023-06-20 10:43 UTC, mirceahasegan approved these changes
Nice! :rocket:

2023-06-20 11:08 UTC, iadmytro approved these changes

2023-06-20 11:11 UTC, merged