Feat/lw 7584 serialization of scripts in tx body
input-output-hk/cardano-js-sdk pull request #837
Opened 2023-08-01 03:08 UTC by AngelCastilloB

# Context

In order to use the SDK in the mobile environment is now a priority to replace the CML library with our custom serialization classes.

# Proposed Solution

Implement the serialization natively in Typescript.

# Important Changes Introduced

- Added a new namespace 'Serialization' to avoid current and future name collisions.
- Added Native and Plutus script serialization.

2023-08-03 14:04 UTC, mkazlauskas requested changes

2023-08-03 14:04 UTC, mkazlauskas commented on packages/core/test/Serialization/Scripts.test.ts
> +        '82008202828200581cb275b08c999097247f7c17e77007c7010cd19f20cc086ad99d3985388201838205190bb88200581c966e394a544f242081e41d1965137b1bb412ac230d40ed5407821c378204190fa0'
Would be great to put in some inline comments about the source (or how test data was produced) for all CBORs and hashes

2023-08-04 05:14 UTC, mkazlauskas approved these changes
Great work!

2023-08-07 07:56 UTC, rhyslbw approved these changes
Great work Angel 🚀

2023-08-07 12:46 UTC, merged