LW-7733 Added custom classes for certificate serialization
input-output-hk/cardano-js-sdk pull request #852
Opened 2023-08-08 13:23 UTC by AngelCastilloB

# Context

In order to use the SDK in the mobile environment is now a priority to replace the CML library with our custom serialization classes.

# Proposed Solution

Implement the serialization natively in Typescript.

# Important Changes Introduced

- Added Certificate serialization classes.
- Update MIR certificate core type

2023-08-10 13:09 UTC, mkazlauskas requested changes

2023-08-10 13:09 UTC, mkazlauskas commented on packages/core/src/Serialization/Certificates/CertificateKind.ts
> + * Certificates are used to register, update, or deregister stake pools, and delegate stake.
I had a question why not consolidate this with `Cardano.CertificateType`, so probably worth adding a comment to explain
```suggestion
 * Certificates are used to register, update, or deregister stake pools, and delegate stake.
 * Values are used for serialization.
```

2023-08-11 07:59 UTC, mkazlauskas approved these changes
Great work! Appreciate the extensive doc comments :muscle:

2023-08-11 12:50 UTC, mirceahasegan approved these changes
Impressive 🧙‍♂️ 👏

2023-08-11 13:29 UTC, merged