Feat/cip 95 dapp e2e tests
input-output-hk/cardano-js-sdk pull request #891
Opened 2023-08-28 14:54 UTC by mirceahasegan

# Context

SDK e2e tests for cip-95 dapp integration.
For now, only the initialization of the test with the enable function is done.
Once CIP-95 functionality is merged, tests will be added in this new test file.

# Proposed Solution
1. Refactor existing web-extension tests to separate test files for: dapp-cip30 and web-extension.
2. Add built cip-95 dapp and a test file that initialises it just as we do for cip-30

# Important Changes Introduced

2023-08-29 05:15 UTC, mkazlauskas approved these changes
Nice refactor :muscle:

2023-08-31 16:50 UTC, mchappell requested changes

2023-08-31 17:13 UTC, mirceahasegan commented on packages/e2e/test/web-extension/dapp-cip95/.DS_Store
I'll remove them at the final squash. Let's leave this comment open as a reminder 😄

2023-08-31 17:21 UTC, mirceahasegan commented on packages/e2e/test/web-extension/dapp-cip95/.DS_Store
Removed here: [5e37c21](https://github.com/input-output-hk/cardano-js-sdk/pull/891/commits/5e37c216c93de6a74620ceee41647f44704469a8).
Marked them to be ignored in the future: [f30edbd](https://github.com/input-output-hk/cardano-js-sdk/pull/891/commits/f30edbd5d54dcf71080c8527f8437a7a68bed03b)

2023-08-31 17:55 UTC, lgobbi-atix approved these changes
LGTM

2023-09-01 05:13 UTC, mkazlauskas commented on packages/e2e/test/web-extension/dapp-cip95/.DS_Store
Please squash the removal commit to 7d37ebd324d69a70219699c7150a4a861deb2dfa

2023-09-01 05:14 UTC, mkazlauskas approved these changes
Great work! :rocket:

2023-09-01 11:05 UTC, mchappell approved these changes
Great work, nice refactoring to make the selectors easier to access between multiple DApps 🥳

2023-09-01 11:06 UTC, merged