Feat/lw 7585 implement serialization of witness set
input-output-hk/cardano-js-sdk pull request #901
Opened 2023-09-02 14:50 UTC by AngelCastilloB

# Context

In order to use the SDK in the mobile environment is now a priority to replace the CML library with our custom serialization classes.

# Proposed Solution

Implement the serialization natively in Typescript.

# Important Changes Introduced

- Added transaction witness set serialization classes.

2023-09-04 20:33 UTC, rhyslbw requested changes
Awesome work @AngelCastilloB 🔥 

It looks like 0f7298aef7cea11973f973398979bff61e9e2940 should be squashed with the first commit though, if the tests were failing without it. It's great to see this implementation has a positive effect on transaction cost 😎

2023-09-04 20:33 UTC, rhyslbw commented on packages/core/src/Serialization/TransactionWitnessSet/TransactionWitnessSet.ts
> + * In Cardano, transactions need multiple types of authentication proofs, these can range
```suggestion
 * In Cardano, transactions have multiple types of authentication proofs, these can range
```

2023-09-05 08:01 UTC, mkazlauskas approved these changes
Great work!

2023-09-05 08:01 UTC, mkazlauskas commented on packages/tx-construction/test/fees/fees.test.ts
> +      expect(fee).toBe(218_763n);
Witness set is now smaller? :mage:

2023-09-05 10:16 UTC, rhyslbw approved these changes

2023-09-05 19:49 UTC, merged