Feat/lw 7586 implement serialization of aux metadata
input-output-hk/cardano-js-sdk pull request #904
Opened 2023-09-05 07:27 UTC by AngelCastilloB

# Context

In order to use the SDK in the mobile environment is now a priority to replace the CML library with our custom serialization classes.

# Proposed Solution

Implement the serialization natively in Typescript.

# Important Changes Introduced

- Added transaction auxiliary data serialization classes.
- Implement hashing functions for transaction types.
- Remove CML as a dependency from the core package.

2023-09-07 05:37 UTC, mkazlauskas requested changes

2023-09-07 05:37 UTC, mkazlauskas commented on packages/core/src/Serialization/PlutusData/PlutusMap.ts
> +    const element = [...this._map.entries()].find((entry) => deepEquals(entry[0], key));
Just a nitpick suggestion, entries is fine too
```suggestion
    const element = [...this._map.keys()].find((mapKey) => deepEquals(mapKey, key));
```

2023-09-07 05:37 UTC, mkazlauskas commented on packages/core/test/Serialization/PlutusData.test.ts
> +      expect(data.get(Serialization.PlutusData.newInteger(1n))).toEqual(Serialization.PlutusData.newInteger(2n));
Would be great to add this assertion to make sure that 1n and 2n PlutusData are not deepEquals. Wouldn't be a bad idea to add `equals` method to all PlutusData classes to be sure it works as expected with all kinds.
```ts
expect(data.get(Serialization.PlutusData.newInteger(2n))).toBeUndefined();
```

2023-09-07 07:08 UTC, mkazlauskas requested changes

2023-09-07 07:08 UTC, mkazlauskas commented on packages/core/src/Serialization/PlutusData/PlutusData.ts
> +  equals(other: PlutusData): boolean {
Even though this is indirectly tested in `PlutusMap.get`, this is a public method that deserves a couple of direct tests

2023-09-07 07:08 UTC, mkazlauskas commented on packages/core/src/Serialization/PlutusData/PlutusData.ts
> +        return HexBlob.fromBytes(this.#bytes!) === HexBlob.fromBytes(other.#bytes!);
Possible optimization here (nitpick :sweat_smile:)
```suggestion
        return this.#bytes && this.#bytes.length === other.#bytes?.length && this.#bytes.every((value, index) => value === other.#bytes![index]);
```

2023-09-07 07:08 UTC, mkazlauskas commented on packages/core/src/Serialization/PlutusData/PlutusData.ts
> +        result = false;
One more nitpick
```suggestion
        return false;
```

2023-09-07 12:30 UTC, mkazlauskas approved these changes
Great work! :rocket: When squashing, please change the `equals` commit type to `feat` as it's really just adding a feature

2023-09-08 08:05 UTC, rhyslbw approved these changes
Fantastic work @AngelCastilloB :mage: :boom:

2023-09-08 08:35 UTC, merged