LW-9018 fix unit tests
input-output-hk/cardano-js-sdk pull request #979
Opened 2023-11-08 16:37 UTC by mirceahasegan

# Context

# Proposed Solution

# Important Changes Introduced

2023-11-08 17:08 UTC, iccicci approved these changes
Simply awesome!
Thank you very much!

2023-11-10 09:32 UTC, mkazlauskas requested changes

2023-11-10 09:32 UTC, mkazlauskas commented on packages/util/src/serializableObject.ts
> +      obj.innerError.data = toSerializableObject(obj.innerError.data);
I think this results in serializing innerError as plain object, which means that it won't get `[transformationTypeKey]: 'Error'` and won't run through `getErrorPrototype`. Maybe we could wrap `serializeError` in a new function that does this recursively.

2023-11-14 09:54 UTC, mkazlauskas approved these changes
Nice work! :rocket:

2023-11-14 17:41 UTC, merged